chat_model:
  init_args:
    model: gemini-pro-latest
    model_provider: openai
    api_key: sk-9Ei9aZqeYEFAfrCb3Wq3aS0JNZ7mtMUUVLU2a2S5WW5JSBd7
    base_url: https://yunwu.ai/v1


image_generator:
  class_path: tools.ImageGeneratorNanobananaYunwuAPI
  init_args:
    api_key: sk-9Ei9aZqeYEFAfrCb3Wq3aS0JNZ7mtMUUVLU2a2S5WW5JSBd7


video_generator:
  class_path: tools.VideoGeneratorVeoYunwuAPI
  init_args:
    api_key: sk-9Ei9aZqeYEFAfrCb3Wq3aS0JNZ7mtMUUVLU2a2S5WW5JSBd7


working_dir: .working_dir/script2video
