chat_model:
  init_args:
    model: deepseek/deepseek-chat-v3.1:free
    model_provider: openai
    api_key: 
    base_url: https://openrouter.ai/api/v1


image_generator:
  class_path: tools.ImageGeneratorNanobananaGoogleAPI
  init_args:
    api_key: 


video_generator:
  class_path: tools.VideoGeneratorVeoGoogleAPI
  init_args:
    api_key: 

working_dir: .working_dir/script2video
